doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    server_version: '5.7'
    types:
      uuid: Symfony\Bridge\Doctrine\Types\UuidType
      PostId: App\Content\Infrastructure\Doctrine\Types\PostIdType
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      ContentBundle:
         type: xml
         dir: Infrastructure/Doctrine/Mappings
         prefix: App\Content\Domain
      OutBoxBundle:
        type: attribute
