framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed
    default_bus: none.bus
    buses:
      none.bus:
        default_middleware: allow_no_handlers
      command.bus:
        middleware:
          - doctrine_ping_connection
          - doctrine_close_connection
          - doctrine_transaction
      event.bus:
        default_middleware: allow_no_handlers
        middleware:
          - validation
      projection.bus:
        default_middleware: allow_no_handlers
        middleware:
          - validation
      outbox.bus:
        default_middleware: allow_no_handlers
        middleware:
          - validation

    transports:
      #commands
      command_async: '%env(MESSENGER_TRANSPORT_DSN)%/commands'
      command_sync: 'sync://'
      #events
      events_async: '%env(MESSENGER_TRANSPORT_DSN)%/events'
      events_sync: 'sync://'
      #projection
      projections_async: '%env(MESSENGER_TRANSPORT_DSN)%/projections'
      projections_sync: 'sync://'
      #outbox
      outbox: '%env(MESSENGER_TRANSPORT_DOCTRINE_DSN)%'

      # failed: 'doctrine://default?queue_name=failed'
      # sync: 'sync://'

    routing:
      # Route your messages to the transports
      'App\Framework\Application\Command\AsyncCommand': command_async
      'App\Framework\Application\Command\Command': command_sync
      'App\Framework\Application\Projection\Projection': projections_async
      'App\Framework\Domain\DomainEvent': outbox

