framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed
    default_bus: none.bus
    buses:
      none.bus:
        default_middleware: allow_no_handlers
      command.bus:
        middleware:
          - doctrine_ping_connection
          - doctrine_close_connection
          - doctrine_transaction
      event.bus:
        default_middleware: allow_no_handlers
        middleware:
          - validation

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      command_async: '%env(MESSENGER_TRANSPORT_DSN)%/commands'
      command_sync: 'sync://'
      # failed: 'doctrine://default?queue_name=failed'
      # sync: 'sync://'
      events_async: '%env(MESSENGER_TRANSPORT_DSN)%/events'
      events_sync: 'sync://'

    routing:
      # Route your messages to the transports
      'App\Framework\Application\Command\AsyncCommand': command_async
      'App\Framework\Application\Command\Command': command_sync
      'App\Framework\Domain\DomainEvent': events_async
