version: '3.9'
services:
  webserver:
    container_name: cms_webserver
    hostname: web-server
#    build:
#      context: ./docker/nginx/local
    image: cms_webserver:latest
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/app
    depends_on:
      - fpm
    restart: unless-stopped
    networks:
      - cms_app
  fpm:
    container_name: cms_app
    hostname: application
#    build:
#      context: .
#      dockerfile: ./docker/php/local/Dockerfile
    image: cms_fpm:latest
    volumes:
      - ./:/var/www/app
      - ./docker/php/local/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/local/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - db
      - redis
      - rabbitmq
    restart: unless-stopped
    networks:
      - cms_app
  db:
    image: mysql:5.7.4
    hostname: database
    container_name: cms_db
    environment:
      - MYSQL_DATABASE=cms
      - MYSQL_USER=cms_admin
      - MYSQL_PASSWORD=cms
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tehran
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - cms_app
  redis:
    image: redis:alpine
    hostname: redis
    container_name: cms_redis
    volumes:
      - redis:/data
    restart: unless-stopped
    networks:
      - cms_app
  db_admin:
    image: phpmyadmin/phpmyadmin
    hostname: phpmyadmin
    container_name: cms_db_admin
    depends_on:
      - db
    ports:
      - "8010:80"
    environment:
      - PMA_ARBITARY=1
    restart: unless-stopped
    networks:
      - cms_app
  rabbitmq:
    image: rabbitmq:3.10-management
    hostname: message-broker
    container_name: cms_message_broker
    ports:
      - "8090:15672"
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - cms_app
volumes:
  db:
  redis:
networks:
  cms_app:
